const { ethers } = require("hardhat");
const fs = require('fs');
const path = require('path');

async function main() {
  console.log("Deploying XelliEscrow contract...");

  const XelliEscrow = await ethers.getContractFactory("XelliEscrow");
  const escrow = await XelliEscrow.deploy();

  await escrow.waitForDeployment();
  const escrowAddress = await escrow.getAddress();

  console.log("XelliEscrow deployed to:", escrowAddress);
  
  // Get network info
  const network = await ethers.provider.getNetwork();
  const chainId = network.chainId.toString();
  
  console.log("Network:", network.name);
  console.log("Chain ID:", chainId);
  
  // Read existing escrow addresses config or create new
  const configPath = path.join(__dirname, '../../frontend/lib/escrowConfig.ts');
  let escrowAddresses = {};
  
  // Try to read existing config if it exists
  if (fs.existsSync(configPath)) {
    try {
      const configContent = fs.readFileSync(configPath, 'utf8');
      // Extract existing addresses from the file (simple regex match)
      const matches = configContent.matchAll(/['"](\d+)['"]:\s*['"](0x[a-fA-F0-9]+)['"]/g);
      for (const match of matches) {
        escrowAddresses[match[1]] = match[2];
      }
    } catch (e) {
      console.log("Could not read existing config, creating new one");
    }
  }
  
  // Update with new address
  escrowAddresses[chainId] = escrowAddresses[chainId] || escrowAddress;
  
  // Write config file
  const configContent = `// Escrow contract addresses per chain
// Auto-generated by deployment script
// Update this file after deploying to each chain

export const ESCROW_ADDRESSES: Record<string, string> = {
  ${Object.entries(escrowAddresses).map(([chainId, address]) => `"${chainId}": "${address}"`).join(',\n  ')}
};

// Chain IDs reference:
// 8453 = Base
// 1 = Ethereum
// 56 = BNB Chain
// 137 = Polygon
`;

  fs.writeFileSync(configPath, configContent);
  
  console.log("\n✅ Escrow address saved to:", configPath);
  console.log("\nNext steps:");
  console.log("1. Deploy to other chains (Base, Ethereum, BNB, Polygon)");
  console.log("2. Update backend/.env with ESCROW_CONTRACT_ADDRESSES");
  console.log("3. Run database migration for escrow_payments table");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });

