// Escrow contract addresses per chain
// Auto-generated by deployment script
// Update this file after deploying to each chain

export const ESCROW_ADDRESSES: Record<string, string> = {
  // Add addresses after deployment:
  // "8453": "0x...",    // Base
  // "1": "0x...",       // Ethereum
  // "56": "0x...",      // BNB Chain
  // "137": "0x...",     // Polygon
};

// Chain IDs reference:
// 8453 = Base
// 1 = Ethereum
// 56 = BNB Chain
// 137 = Polygon

